import "google/protobuf/empty.proto";

option go_package = "github.com/stesla/iris/api";

service Upstreams {
  rpc AddUpstream (AddUpstreamRequest) returns (google.protobuf.Empty) {}
  rpc EditUpstream(EditUpstreamRequest) returns (google.protobuf.Empty) {}
  rpc ListUpstreams (google.protobuf.Empty) returns (ListUpstreamsResponse) {}
}

message Upstream {
  required string name = 1;
  required string address = 2;
  required string login = 3;
}

message AddUpstreamRequest {
  required Upstream upstream = 1;
  required string password = 3;
  optional string script = 4;
}

message EditUpstreamRequest {
  required string name = 1;
  required string password = 2;
  optional string new_name = 3;
  optional string new_password = 4;
  optional string address = 5;
  optional string login = 6;
  optional string script = 7;
}

message ListUpstreamsResponse {
  repeated Upstream upstreams = 1;
}
