// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc2
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUpstreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Address       *string                `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	Password      *string                `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	Script        *string                `protobuf:"bytes,4,req,name=script" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUpstreamRequest) Reset() {
	*x = AddUpstreamRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUpstreamRequest) ProtoMessage() {}

func (x *AddUpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUpstreamRequest.ProtoReflect.Descriptor instead.
func (*AddUpstreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *AddUpstreamRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AddUpstreamRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *AddUpstreamRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *AddUpstreamRequest) GetScript() string {
	if x != nil && x.Script != nil {
		return *x.Script
	}
	return ""
}

type ListUpstreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upstreams     []string               `protobuf:"bytes,1,rep,name=upstreams" json:"upstreams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpstreamResponse) Reset() {
	*x = ListUpstreamResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpstreamResponse) ProtoMessage() {}

func (x *ListUpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpstreamResponse.ProtoReflect.Descriptor instead.
func (*ListUpstreamResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListUpstreamResponse) GetUpstreams() []string {
	if x != nil {
		return x.Upstreams
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x1a\x1bgoogle/protobuf/empty.proto\"v\n" +
	"\x12AddUpstreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x02(\tR\aaddress\x12\x1a\n" +
	"\bpassword\x18\x03 \x02(\tR\bpassword\x12\x16\n" +
	"\x06script\x18\x04 \x02(\tR\x06script\"4\n" +
	"\x14ListUpstreamResponse\x12\x1c\n" +
	"\tupstreams\x18\x01 \x03(\tR\tupstreams2\x8b\x01\n" +
	"\tUpstreams\x12<\n" +
	"\vAddUpstream\x12\x13.AddUpstreamRequest\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\rListUpstreams\x12\x16.google.protobuf.Empty\x1a\x15.ListUpstreamResponse\"\x00B\x1cZ\x1agithub.com/stesla/iris/api"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_goTypes = []any{
	(*AddUpstreamRequest)(nil),   // 0: AddUpstreamRequest
	(*ListUpstreamResponse)(nil), // 1: ListUpstreamResponse
	(*emptypb.Empty)(nil),        // 2: google.protobuf.Empty
}
var file_api_proto_depIdxs = []int32{
	0, // 0: Upstreams.AddUpstream:input_type -> AddUpstreamRequest
	2, // 1: Upstreams.ListUpstreams:input_type -> google.protobuf.Empty
	2, // 2: Upstreams.AddUpstream:output_type -> google.protobuf.Empty
	1, // 3: Upstreams.ListUpstreams:output_type -> ListUpstreamResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
