// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc2
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Upstreams_AddUpstream_FullMethodName   = "/Upstreams/AddUpstream"
	Upstreams_ListUpstreams_FullMethodName = "/Upstreams/ListUpstreams"
)

// UpstreamsClient is the client API for Upstreams service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpstreamsClient interface {
	AddUpstream(ctx context.Context, in *AddUpstreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListUpstreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUpstreamsResponse, error)
}

type upstreamsClient struct {
	cc grpc.ClientConnInterface
}

func NewUpstreamsClient(cc grpc.ClientConnInterface) UpstreamsClient {
	return &upstreamsClient{cc}
}

func (c *upstreamsClient) AddUpstream(ctx context.Context, in *AddUpstreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Upstreams_AddUpstream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upstreamsClient) ListUpstreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUpstreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUpstreamsResponse)
	err := c.cc.Invoke(ctx, Upstreams_ListUpstreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpstreamsServer is the server API for Upstreams service.
// All implementations must embed UnimplementedUpstreamsServer
// for forward compatibility.
type UpstreamsServer interface {
	AddUpstream(context.Context, *AddUpstreamRequest) (*emptypb.Empty, error)
	ListUpstreams(context.Context, *emptypb.Empty) (*ListUpstreamsResponse, error)
	mustEmbedUnimplementedUpstreamsServer()
}

// UnimplementedUpstreamsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpstreamsServer struct{}

func (UnimplementedUpstreamsServer) AddUpstream(context.Context, *AddUpstreamRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUpstream not implemented")
}
func (UnimplementedUpstreamsServer) ListUpstreams(context.Context, *emptypb.Empty) (*ListUpstreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUpstreams not implemented")
}
func (UnimplementedUpstreamsServer) mustEmbedUnimplementedUpstreamsServer() {}
func (UnimplementedUpstreamsServer) testEmbeddedByValue()                   {}

// UnsafeUpstreamsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpstreamsServer will
// result in compilation errors.
type UnsafeUpstreamsServer interface {
	mustEmbedUnimplementedUpstreamsServer()
}

func RegisterUpstreamsServer(s grpc.ServiceRegistrar, srv UpstreamsServer) {
	// If the following call panics, it indicates UnimplementedUpstreamsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Upstreams_ServiceDesc, srv)
}

func _Upstreams_AddUpstream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUpstreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamsServer).AddUpstream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Upstreams_AddUpstream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamsServer).AddUpstream(ctx, req.(*AddUpstreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Upstreams_ListUpstreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamsServer).ListUpstreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Upstreams_ListUpstreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamsServer).ListUpstreams(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Upstreams_ServiceDesc is the grpc.ServiceDesc for Upstreams service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Upstreams_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Upstreams",
	HandlerType: (*UpstreamsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUpstream",
			Handler:    _Upstreams_AddUpstream_Handler,
		},
		{
			MethodName: "ListUpstreams",
			Handler:    _Upstreams_ListUpstreams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
